### ISSUE TITLE
Not working with AOT

### ISSUE THREAD

**Issue by Ks89** [bbottema/ng2-simple-page-scroll#15]
When I try to compile with AOT (with angular 2.4.8), I get this:

```
Starting compilation using the angular compiler.
Failed on type {"filePath":"/Users/user/myproject/node_modules/ng2-simple-page-scroll/src/ng2-simple-page-scroll.service.d.ts","name":"SimplePageScrollService","members":[]} with error Error: Error encountered resolving symbol values statically. Could not resolve type Document (position 13:52 in the original .ts file), resolving symbol SimplePageScrollService in /Users/user/myproject/node_modules/ng2-simple-page-scroll/src/ng2-simple-page-scroll.service.d.ts
Angular compilation done, starting webpack bundling.
Error: Error encountered resolving symbol values statically. Could not resolve type Document (position 13:52 in the original .ts file), resolving symbol SimplePageScrollService in /Users/user/myproject/node_modules/ng2-simple-page-scroll/src/ng2-simple-page-scroll.service.d.ts
    at positionalError (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25944:39)
    at simplifyInContext (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25781:31)
    at StaticReflector.simplify (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.parameters (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25349:69)
    at CompileMetadataResolver._getDependenciesMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18606:75)
    at CompileMetadataResolver._getTypeMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18533:30)
    at CompileMetadataResolver._getInjectableMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18521:25)
    at CompileMetadataResolver.getProviderMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18763:44)
    at /Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18721:53
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18688:23)
    at /Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18295:67
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:18286:53)
    at addNgModule (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at /Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)
    at _createNgModules (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25063:30)
    at analyzeNgModules (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:24938:18)
    at analyzeAndValidateNgModules (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:24948:39)
    at AotCompiler.compileAll (/Users/user/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:24672:22)
    at CodeGenerator.codegen (/Users/user/myproject/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at /Users/user/myproject/node_modules/ngc-webpack/src/main.js:12:103
    at Object.main (/Users/user/myproject/node_modules/@angular/tsc-wrapped/src/main.js:47:16)
    at Object.runInternal (/Users/user/myproject/node_modules/ngc-webpack/src/main.js:16:27)
    at NgcWebpackPlugin.run (/Users/user/myproject/node_modules/ngc-webpack/src/plugin.js:44:20)
    at Compiler.<anonymous> (/Users/user/myproject/node_modules/ngc-webpack/src/plugin.js:23:73)
    at Compiler.applyPluginsAsyncSeries (/Users/user/myproject/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/user/myproject/node_modules/webpack/lib/Compiler.js:214:8
    at next (/Users/user/myproject/node_modules/tapable/lib/Tapable.js:138:11)
```

**Comment by ardiadrianadri** [comment]
I have the same problem

**Comment by guycollinson** [comment]
The problem has been temporarily resolved in the ng2-page-scroll component from which this is forked, by replacing document type with any. Can you do the same here please
[https://github.com/Nolanus/ng2-page-scroll/issues/35#issuecomment-250939092](url)
